CREATE TABLE [dbo].[BAIRROS] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL,
    [NOME_BAIRRO] VARCHAR (45) NOT NULL,
    [CIDADE_ID]   INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BAIRROS_CIDADE] FOREIGN KEY ([CIDADE_ID]) REFERENCES [dbo].[CIDADES] ([ID])
);
CREATE TABLE [dbo].[CIDADES] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL,
    [NOME_CIDADE] VARCHAR (45) NOT NULL,
    [ESTADO_ID]   INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CIDADES_ESTADO] FOREIGN KEY ([ESTADO_ID]) REFERENCES [dbo].[ESTADOS] ([ID])
);
CREATE TABLE [dbo].[CLIENTES] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [NOME]            VARCHAR (100) NOT NULL,
    [RG]              VARCHAR (11)  NOT NULL,
    [CPF]             VARCHAR (14)  NULL,
    [TELEFONE1]       VARCHAR (45)  NOT NULL,
    [TELEFONE2]       VARCHAR (45)  NOT NULL,
    [EMAIL]           VARCHAR (100) NOT NULL,
    [PONTOS]          INT           DEFAULT ((0)) NOT NULL,
    [TIPO_CLIENTE_ID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_CLIENTES_EMAIL] UNIQUE NONCLUSTERED ([EMAIL] ASC),
    CONSTRAINT [UQ_CLIENTES_CPF] UNIQUE NONCLUSTERED ([CPF] ASC),
    CONSTRAINT [FK_CLIENTES_TIPO_CLIENTE_ID] FOREIGN KEY ([TIPO_CLIENTE_ID]) REFERENCES [dbo].[TIPOS_CLIENTES] ([ID])
);
CREATE TABLE [dbo].[ENDERECOS] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL,
    [CEP]         INT          NOT NULL,
    [LOGRADOURO]  VARCHAR (45) NOT NULL,
    [NUMERO_CASA] VARCHAR (10) NOT NULL,
    [BAIRRO_ID]   INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ENDERECOS_BAIRRO] FOREIGN KEY ([BAIRRO_ID]) REFERENCES [dbo].[BAIRROS] ([ID])
);
CREATE TABLE [dbo].[ENTRADAS] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [PRECO]           FLOAT (53)    NOT NULL,
    [FORNECEDOR_ID] INT           NOT NULL,
    [FUNCIONARIO_ID] INT           NOT NULL,
    [DATA_ENTRADA]    DATETIME2 (7) DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ENTRADAS_FORNECEDOR] FOREIGN KEY ([FORNECEDOR_ID]) REFERENCES [dbo].[FORNECEDORES] ([ID]),
    CONSTRAINT [FK_ENTRADAS_FUNCIONARIO] FOREIGN KEY ([FUNCIONARIO_ID]) REFERENCES [dbo].[FUNCIONARIOS] ([ID])
);
CREATE TABLE [dbo].[ESTADOS] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL,
    [NOME_ESTADO] VARCHAR (45) NOT NULL,
    [SIGLA]       VARCHAR (2)  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_ESTADOS_SIGLA] UNIQUE NONCLUSTERED ([SIGLA] ASC)
);
CREATE TABLE [dbo].[FORMAS_PAGAMENTO] (
    [ID]   INT          IDENTITY (1, 1) NOT NULL,
    [NOME] VARCHAR (45) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
CREATE TABLE [dbo].[FORNECEDORES] (
    [ID]           INT          IDENTITY (1, 1) NOT NULL,
    [RAZAO_SOCIAL] VARCHAR (45) NOT NULL,
    [CNPJ]         VARCHAR (45) NOT NULL,
    [NOME_CONTATO] VARCHAR (45) NOT NULL,
    [TELEFONE]     VARCHAR (45) NOT NULL,
    [EMAIL]        VARCHAR (45) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_FORNECEDORES_EMAIL] UNIQUE NONCLUSTERED ([EMAIL] ASC),
    CONSTRAINT [UQ_FORNECEDORES_CNPJ] UNIQUE NONCLUSTERED ([CNPJ] ASC)
);
CREATE TABLE [dbo].[FUNCIONARIOS] (
    [ID]                  INT           IDENTITY (1, 1) NOT NULL,
    [NOME]                VARCHAR (100) NOT NULL,
    [CPF]                 VARCHAR (14)  NOT NULL,
    [RG]                  VARCHAR (45)  NOT NULL,
    [TELEFONE]            VARCHAR (45)  NOT NULL,
    [EMAIL]               VARCHAR (45)  NOT NULL,
    [SENHA]               VARCHAR (45)  NOT NULL,
    [ENDERECO_ID]         INT           NOT NULL,
    [TIPO_FUNCIONARIO_ID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_FUNCIONARIOS_CPF] UNIQUE NONCLUSTERED ([CPF] ASC),
    CONSTRAINT [UQ_FUNCIONARIOS_EMAIL] UNIQUE NONCLUSTERED ([EMAIL] ASC),
    CONSTRAINT [FK_FUNCIONARIOS_ENDERECO] FOREIGN KEY ([ENDERECO_ID]) REFERENCES [dbo].[ENDERECO] ([ID]),
    CONSTRAINT [FK_FUNCIONARIOS_TIPO_FUNCIONARIO_ID] FOREIGN KEY ([TIPO_FUNCIONARIO_ID]) REFERENCES [dbo].[TIPOS_FUNCIONARIOS] ([ID])
);
CREATE TABLE [dbo].[LABORATORIOS] (
    [ID]   INT          IDENTITY (1, 1) NOT NULL,
    [NOME] VARCHAR (45) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
CREATE TABLE [dbo].[PRODUTOS] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [NOME]            VARCHAR (100) NOT NULL,
    [DESCRICAO]       VARCHAR (200) NOT NULL,
    [QTD_ESTOQUE]     FLOAT (53)    NOT NULL,
    [LABORATORIO_ID]  INT           NOT NULL,
    [TIPO_UNIDADE_ID] INT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PRODUTOS_LABORATORIO_ID] FOREIGN KEY ([LABORATORIO_ID]) REFERENCES [dbo].[LABORATORIOS] ([ID]),
    CONSTRAINT [FK_PRODUTOS_TIPO_UNIDADE] FOREIGN KEY ([TIPO_UNIDADE_ID]) REFERENCES [dbo].[TIPOS_UNIDADES] ([ID])
);
CREATE TABLE [dbo].[PRODUTOS_ENTRADAS] (
    [ENTRADA_ID]     INT        NOT NULL,
    [PRODUTO_ID]    INT        NOT NULL,
    [QUANTIDADE]     FLOAT (53) NOT NULL,
    [VALOR_UNITARIO] FLOAT (53) NOT NULL,
    PRIMARY KEY CLUSTERED ([ENTRADA_ID] ASC, [PRODUTOS_ID] ASC),
    CONSTRAINT [FK_PRODUTOS_ENTRADAS_PRODUTOS] FOREIGN KEY ([PRODUTO_ID]) REFERENCES [dbo].[PRODUTOS] ([ID]),
    CONSTRAINT [FK_PRODUTOS_ENTRADAS_ENTRADA] FOREIGN KEY ([ENTRADA_ID]) REFERENCES [dbo].[ENTRADAS] ([ID])
);
CREATE TABLE [dbo].[PRODUTOS_SAIDA] (
    [PRODUTOS_ID]    INT        NOT NULL,
    [SAIDA_ID]       INT        NOT NULL,
    [QUATIDADE]      FLOAT (53) NOT NULL,
    [VALOR_UNITARIO] FLOAT (53) NOT NULL,
    PRIMARY KEY CLUSTERED ([PRODUTOS_ID] ASC, [SAIDA_ID] ASC),
    CONSTRAINT [FK_PRODUTOS_SAIDA_PRODUTOS] FOREIGN KEY ([PRODUTO_ID]) REFERENCES [dbo].[PRODUTOS] ([ID]),
    CONSTRAINT [FK_PRODUTOS_SAIDA_SAIDA] FOREIGN KEY ([SAIDA_ID]) REFERENCES [dbo].[SAIDAS] ([ID])
);
CREATE TABLE [dbo].[SAIDAS] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [VALOR]              FLOAT (53)    NOT NULL,
    [CLIENTE_ID]        INT           NOT NULL,
    [FUNCIONARIOS_ID]    INT           NOT NULL,
    [DATA_SAIDA]         DATETIME2 (7) DEFAULT (getdate()) NOT NULL,
    [FORMA_PAGAMENTO_ID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SAIDAS_FUNCIONARIO] FOREIGN KEY ([FUNCIONARIO_ID]) REFERENCES [dbo].[FUNCIONARIOS] ([ID]),
    CONSTRAINT [FK_SAIDAS_CLIENTE] FOREIGN KEY ([CLIENTE_ID]) REFERENCES [dbo].[CLIENTES] ([ID]),
    CONSTRAINT [FK_SAIDAS_FORMA_PAGAMENTO_ID] FOREIGN KEY ([FORMA_PAGAMENTO_ID]) REFERENCES [dbo].[FORMAS_PAGAMENTO] ([ID])
);
CREATE TABLE [dbo].[TIPOS_CLIENTES] (
    [ID]   INT          IDENTITY (1, 1) NOT NULL,
    [NOME] VARCHAR (45) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
CREATE TABLE [dbo].[TIPOS_FUNCIONARIOS] (
    [ID]   INT          IDENTITY (1, 1) NOT NULL,
    [NOME] VARCHAR (45) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
CREATE TABLE [dbo].[TIPOS_UNIDADES] (
    [ID]   INT          IDENTITY (1, 1) NOT NULL,
    [NOME] VARCHAR (45) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);